include:
  - project: 'project-version3/erp-infra/gitlab-ci'
    file:
      - 'sonarqube-check.yml'
      - 'build-image.yml'
      - 'deploy-image.yml'
      - 'purge.yml'

stages:
  - test
  - build
  - deploy
  - purge

before_script:
  - >
    if [ "$CI_COMMIT_BRANCH" == "uat" ]; then 
      sed -i "s/<SUBDOMAIN>/${DOMAIN_UAT}/g" src/index.ejs
    else
      sed -i "s/<SUBDOMAIN>/${DOMAIN_DEV}/g" src/index.ejs
    fi
